#!/usr/bin/env bash

#is there some way I can find the directory holding this shell script?

CMSSW_BASE=$PWD
export CMSSW_BASE
ROOTSYS=$CMSSW_BASE/external/root 
export ROOTSYS
LD_LIBRARY_PATH=${CMSSW_BASE}:${CMSSW_BASE}/external/lib:${ROOTSYS}/lib
export LD_LIBRARY_PATH
./cmsShow.exe $@
