#!/usr/bin/env bash

#strip of the directory name for this shell script
SHELLDIR=`dirname $0`
export SHELLDIR
#if no directory specified we need to use the local directory
if [ ! -n "$SHELLDIR" ] ; then
  SHELLDIR=.
  export SHELLDIR
fi
CMSSW_BASE=$SHELLDIR
export CMSSW_BASE
ROOTSYS=$CMSSW_BASE/external/root 
export ROOTSYS
LD_LIBRARY_PATH=${CMSSW_BASE}:${CMSSW_BASE}/external/lib:${ROOTSYS}/lib
export LD_LIBRARY_PATH
DYLD_LIBRARY_PATH=${CMSSW_BASE}:${CMSSW_BASE}/external/lib:${ROOTSYS}/lib
export DYLD_LIBRARY_PATH
echo "Loading cmsShow"
if [ "`echo $@ | awk '/\-\-soft/'`" != "" ] ; then
  LIBGL_DRIVERS_PATH=/tmp/
  export LIBGL_DRIVERS_PATH
fi
$CMSSW_BASE/cmsShow.exe $@
